In [1]:
import numpy as np

# Chapter 2<br>Systems of Equations

## 2.2 The LU Factorization

### Q. 1

In [2]:
def LU(A):
    m = A.shape[0]
    L = np.identity(m)
    U = A.copy()

    for i in range(m):
        for j in range(i+1, m):
            a = U[j, i] / U[i, i]
            L[j, i] = a
            U[j] -= a * U[i]
    
    return L, U

In [3]:
# (a)
A = np.array([[1, 2], [3, 4]], dtype=float)
L, U = LU(A)

print("L:\n", L)
print("U:\n", U)
print("LU =\n", np.dot(L, U))
print("A == LU:", (np.dot(L, U) == A).all())

L:
 [[1. 0.]
 [3. 1.]]
U:
 [[ 1.  2.]
 [ 0. -2.]]
LU =
 [[1. 2.]
 [3. 4.]]
A == LU: True


In [4]:
# (b)
A = np.array([[1, 3], [2, 2]], dtype=float)
L, U = LU(A)

print("L:\n", L)
print("U:\n", U)
print("LU =\n", np.dot(L, U))
print("A == LU:", (np.dot(L, U) == A).all())

L:
 [[1. 0.]
 [2. 1.]]
U:
 [[ 1.  3.]
 [ 0. -4.]]
LU =
 [[1. 3.]
 [2. 2.]]
A == LU: True


In [5]:
# (c)
A = np.array([[3, -4], [-5, 2]], dtype=float)
L, U = LU(A)

print("L:\n", L)
print("U:\n", U)
print("LU =\n", np.dot(L, U))
print("A == LU:", (np.dot(L, U) == A).all())

L:
 [[ 1.          0.        ]
 [-1.66666667  1.        ]]
U:
 [[ 3.         -4.        ]
 [ 0.         -4.66666667]]
LU =
 [[ 3. -4.]
 [-5.  2.]]
A == LU: True


### Q. 2

In [6]:
# (a)
A = np.array([[3, 1, 2], [6, 3, 4], [3, 1, 5]], dtype=float)
L, U = LU(A)

print("L:\n", L)
print("U:\n", U)
print("LU =\n", np.dot(L, U))
print("A == LU:", (np.dot(L, U) == A).all())

L:
 [[1. 0. 0.]
 [2. 1. 0.]
 [1. 0. 1.]]
U:
 [[3. 1. 2.]
 [0. 1. 0.]
 [0. 0. 3.]]
LU =
 [[3. 1. 2.]
 [6. 3. 4.]
 [3. 1. 5.]]
A == LU: True


In [7]:
# (a)
A = np.array([[4, 2, 0], [4, 4, 2], [2, 2, 3]], dtype=float)
L, U = LU(A)

print("L:\n", L)
print("U:\n", U)
print("LU =\n", np.dot(L, U))
print("A == LU:", (np.dot(L, U) == A).all())

L:
 [[1.  0.  0. ]
 [1.  1.  0. ]
 [0.5 0.5 1. ]]
U:
 [[4. 2. 0.]
 [0. 2. 2.]
 [0. 0. 2.]]
LU =
 [[4. 2. 0.]
 [4. 4. 2.]
 [2. 2. 3.]]
A == LU: True


In [8]:
# (c)
A = np.array([[1, -1, 1, 2], [0, 2, 1, 0], [1, 3, 4, 4], [0, 2, 1, -1]], dtype=float)
L, U = LU(A)

print("L:\n", L)
print("U:\n", U)
print("LU =\n", np.dot(L, U))
print("A == LU:", (np.dot(L, U) == A).all())

L:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [1. 2. 1. 0.]
 [0. 1. 0. 1.]]
U:
 [[ 1. -1.  1.  2.]
 [ 0.  2.  1.  0.]
 [ 0.  0.  1.  2.]
 [ 0.  0.  0. -1.]]
LU =
 [[ 1. -1.  1.  2.]
 [ 0.  2.  1.  0.]
 [ 1.  3.  4.  4.]
 [ 0.  2.  1. -1.]]
A == LU: True


### Q. 3

In [9]:
# (a)
A = np.array([[3, 7], [6, 1]], dtype=float)
b = np.array([1, -11])
m = A.shape[0]

L, U = LU(A)

In [10]:
c = b.copy()
for i in range(m):
    for j in range(i+1, m):
        c[j] -= L[j, i]*c[i]

x = c.copy()
for i in range(m-1, -1, -1):
    x[i] /= U[i, i]
    for j in range(i):
        x[j] -= U[j, i]*x[i]

print("x:", x)
print("Ax = ", np.dot(A, x))

x: [-2  1]
Ax =  [  1. -11.]


In [11]:
# (b)
A = np.array([[2, 3], [4, 7]], dtype=float)
b = np.array([1, 3])
m = A.shape[0]

L, U = LU(A)

In [12]:
c = b.copy()
for i in range(m):
    for j in range(i+1, m):
        c[j] -= L[j, i]*c[i]

x = c.copy()
for i in range(m-1, -1, -1):
    x[i] /= U[i, i]
    for j in range(i):
        x[j] -= U[j, i]*x[i]

print("x:", x)
print("Ax = ", np.dot(A, x))

x: [-1  1]
Ax =  [1. 3.]


### Q. 4

In [13]:
# (a)
A = np.array([[3, 1, 2], [6, 3, 4], [3, 1, 5]], dtype=float)
b = np.array([0, 1, 3])
m = A.shape[0]

L, U = LU(A)

In [14]:
c = b.copy()
for i in range(m):
    for j in range(i+1, m):
        c[j] -= L[j, i]*c[i]

x = c.copy()
for i in range(m-1, -1, -1):
    x[i] /= U[i, i]
    for j in range(i):
        x[j] -= U[j, i]*x[i]

print("x:", x)
print("Ax = ", np.dot(A, x))

x: [-1  1  1]
Ax =  [0. 1. 3.]


In [15]:
# (b)
A = np.array([[4, 2, 0], [4, 4, 2], [2, 2, 3]], dtype=float)
b = np.array([2, 4, 6])
m = A.shape[0]

L, U = LU(A)

In [16]:
c = b.copy()
for i in range(m):
    for j in range(i+1, m):
        c[j] -= L[j, i]*c[i]

x = c.copy()
for i in range(m-1, -1, -1):
    x[i] /= U[i, i]
    for j in range(i):
        x[j] -= U[j, i]*x[i]

print("x:", x)
print("Ax = ", np.dot(A, x))

x: [ 1 -1  2]
Ax =  [2. 4. 6.]


### Q. 5

In [17]:
L = np.array([[1, 0, 0, 0], [0, 1, 0, 0], [1, 3, 1, 0], [4, 1, 2, 1]], dtype=float)
U = np.array([[2, 1, 0, 0], [0, 1, 2, 0], [0, 0, -1, 1], [0, 0, 0, 1]], dtype=float)
b = np.array([1, 1, 2, 0])
m = 4

In [18]:
c = b.copy()
for i in range(m):
    for j in range(i+1, m):
        c[j] -= L[j, i]*c[i]

x = c.copy()
for i in range(m-1, -1, -1):
    x[i] /= U[i, i]
    for j in range(i):
        x[j] -= U[j, i]*x[i]

print("x:", x)
print("Ax = ", L.dot(U).dot(x))

x: [ 1 -1  1 -1]
Ax =  [1. 1. 2. 0.]


### Q. 6

### Q. 7

### Q. 8

### Q. 9