In [1]:
import numpy as np

# Chapter 4<br>Least Squares

## 4.3 QR Factorization

In [2]:
def norm(x):
    return np.sqrt(sum(x**2))

### Q. 1

In [3]:
def QR_classical(A, reduced=False):
    m, n = A.shape

    if not reduced:
        Q = np.zeros((m, m))
        R = np.zeros((m, n))
        while True:
            A_new = np.concatenate((A, np.random.randn(m, m-n)), axis=1)
            if np.linalg.det(A_new) != 0:
                A = A_new
                k = m
                break
    else:
        Q = np.zeros((m, n))
        R = np.zeros((n, n))
        k = n

    r = norm(A[:, 0])
    Q[:, 0] = A[:, 0] / r
    R[0, 0] = r

    for i in range(1, k):
        y = A[:, i]
        for j in range(i):
            r = np.dot(Q[:, j], A[:, i])
            y = y - r*Q[:, j]
            try:
                R[j, i] = r
            except:
                pass
        r = norm(y)
        Q[:, i] = y / r
        try:
            R[i, i] = r
        except:
            pass
        
    return Q, R

In [4]:
# (a)
A = np.array([[4, 0], [3, 1]])
Q, R = QR_classical(A, reduced=True)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[ 0.8 -0.6]
 [ 0.6  0.8]]
R:
 [[5.  0.6]
 [0.  0.8]]


In [5]:
# (b)
A = np.array([[1, 2], [1, 1]])
Q, R = QR_classical(A, reduced=True)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
R:
 [[1.41421356 2.12132034]
 [0.         0.70710678]]


In [6]:
# (c)
A = np.array([[2, 1], [1, -1], [2, 1]])
Q, R = QR_classical(A, reduced=True)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[ 0.66666667  0.23570226]
 [ 0.33333333 -0.94280904]
 [ 0.66666667  0.23570226]]
R:
 [[3.         1.        ]
 [0.         1.41421356]]


In [7]:
# (d)
A = np.array([[4, 8, 1], [0, 2, -2], [3, 6, 7]])
Q, R = QR_classical(A, reduced=True)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[ 0.8  0.  -0.6]
 [ 0.   1.   0. ]
 [ 0.6  0.   0.8]]
R:
 [[ 5. 10.  5.]
 [ 0.  2. -2.]
 [ 0.  0.  5.]]


### Q. 2

In [8]:
def QR_modified(A, reduced=False):
    m, n = A.shape

    if not reduced:
        Q = np.zeros((m, m))
        R = np.zeros((m, n))
        while True:
            A_new = np.concatenate((A, np.random.randn(m, m-n)), axis=1)
            if np.linalg.det(A_new) != 0:
                A = A_new
                k = m
                break
    else:
        Q = np.zeros((m, n))
        R = np.zeros((n, n))
        k = n

    r = norm(A[:, 0])
    Q[:, 0] = A[:, 0] / r
    R[0, 0] = r

    for i in range(1, k):
        y = A[:, i]
        for j in range(i):
            r = np.dot(Q[:, j], y)
            y = y - r*Q[:, j]
            try:
                R[j, i] = r
            except:
                pass
        r = norm(y)
        Q[:, i] = y / r
        try:
            R[i, i] = r
        except:
            pass

    return Q, R

In [9]:
# (a)
A = np.array([[4, 0], [3, 1]])
Q, R = QR_modified(A, reduced=True)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[ 0.8 -0.6]
 [ 0.6  0.8]]
R:
 [[5.  0.6]
 [0.  0.8]]


In [10]:
# (b)
A = np.array([[1, 2], [1, 1]])
Q, R = QR_modified(A, reduced=True)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
R:
 [[1.41421356 2.12132034]
 [0.         0.70710678]]


In [11]:
# (c)
A = np.array([[2, 1], [1, -1], [2, 1]])
Q, R = QR_modified(A, reduced=True)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[ 0.66666667  0.23570226]
 [ 0.33333333 -0.94280904]
 [ 0.66666667  0.23570226]]
R:
 [[3.         1.        ]
 [0.         1.41421356]]


In [12]:
# (d)
A = np.array([[4, 8, 1], [0, 2, -2], [3, 6, 7]])
Q, R = QR_modified(A, reduced=True)
print("Q:\n", Q)
print("R:\n", R)

Q:
 [[ 0.8  0.  -0.6]
 [ 0.   1.   0. ]
 [ 0.6  0.   0.8]]
R:
 [[ 5. 10.  5.]
 [ 0.  2. -2.]
 [ 0.  0.  5.]]


### Q. 3

In [13]:
def QR_Householder(A, reduced=False):
    m, n = np.shape(A)
    H = np.tile(np.identity(m), (n, 1, 1))
    R = A.copy()

    for i in range(n):
        A_i = R[i:, i]
        w = np.zeros(m - i)
        w[0] = norm(A_i) * (2*(A_i[0] < 0) - 1)

        v = (A_i - w).reshape(-1, 1)
        P = np.dot(v, v.T) / norm(v)**2

        H[i, i:, i:] -= 2*P
        R = np.dot(H[i], R)
    Q = np.linalg.multi_dot(H)
    
    if reduced:
        return Q[:, :n], R[:n, :n]
    
    return Q, R

In [14]:
# (a)
A = np.array([[4, 0], [3, 1]])
Q, R = QR_Householder(A, reduced=True)
print("Q:\n", Q.round(10))
print("R:\n", R.round(10))

Q:
 [[-0.8  0.6]
 [-0.6 -0.8]]
R:
 [[-5.  -0.6]
 [-0.  -0.8]]


In [15]:
# (b)
A = np.array([[1, 2], [1, 1]])
Q, R = QR_Householder(A, reduced=True)
print("Q:\n", Q.round(10))
print("R:\n", R.round(10))

Q:
 [[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]
R:
 [[-1.41421356 -2.12132034]
 [-0.          0.70710678]]


In [16]:
# (c)
A = np.array([[2, 1], [1, -1], [2, 1]])
Q, R = QR_Householder(A, reduced=True)
print("Q:\n", Q.round(10))
print("R:\n", R.round(10))

Q:
 [[-0.66666667  0.23570226]
 [-0.33333333 -0.94280904]
 [-0.66666667  0.23570226]]
R:
 [[-3.         -1.        ]
 [-0.          1.41421356]]


In [17]:
# (d)
A = np.array([[4, 8, 1], [0, 2, -2], [3, 6, 7]])
Q, R = QR_Householder(A, reduced=True)
print("Q:\n", Q.round(10))
print("R:\n", R.round(10))

Q:
 [[-0.8  0.   0.6]
 [ 0.  -1.   0. ]
 [-0.6 -0.  -0.8]]
R:
 [[ -5. -10.  -5.]
 [ -0.  -2.   2.]
 [ -0.   0.  -5.]]


### Q. 4

In [18]:
# (a)

Classcal QR Decomposition<br>(1)

In [19]:
A = np.array([[4, 0], [3, 1]])

Q, R = QR_classical(A)
print("Classcal method.")
print("Q:\n", Q)
print("R:\n", R, "\n")

Q, R = np.linalg.qr(A, 'complete')
print("Numpy function.")
print("Q:\n", Q)
print("R:\n", R)

Classcal method.
Q:
 [[ 0.8 -0.6]
 [ 0.6  0.8]]
R:
 [[5.  0.6]
 [0.  0.8]] 

Numpy function.
Q:
 [[-0.8 -0.6]
 [-0.6  0.8]]
R:
 [[-5.  -0.6]
 [ 0.   0.8]]


(2)

In [20]:
A = np.array([[1, 2], [1, 1]])

Q, R = QR_classical(A)
print("Classcal method.")
print("Q:\n", Q)
print("R:\n", R, "\n")

Q, R = np.linalg.qr(A, 'complete')
print("Numpy function.")
print("Q:\n", Q)
print("R:\n", R)

Classcal method.
Q:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
R:
 [[1.41421356 2.12132034]
 [0.         0.70710678]] 

Numpy function.
Q:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
R:
 [[-1.41421356 -2.12132034]
 [ 0.         -0.70710678]]


(3)

In [21]:
A = np.array([[2, 1], [1, -1], [2, 1]])

Q, R = QR_classical(A)
print("Classcal method.")
print("Q:\n", Q)
print("R:\n", R, "\n")

Q, R = np.linalg.qr(A, 'complete')
print("Numpy function.")
print("Q:\n", Q)
print("R:\n", R)

Classcal method.
Q:
 [[ 6.66666667e-01  2.35702260e-01  7.07106781e-01]
 [ 3.33333333e-01 -9.42809042e-01 -2.10153194e-16]
 [ 6.66666667e-01  2.35702260e-01 -7.07106781e-01]]
R:
 [[3.         1.        ]
 [0.         1.41421356]
 [0.         0.        ]] 

Numpy function.
Q:
 [[-6.66666667e-01  2.35702260e-01 -7.07106781e-01]
 [-3.33333333e-01 -9.42809042e-01 -2.49800181e-16]
 [-6.66666667e-01  2.35702260e-01  7.07106781e-01]]
R:
 [[-3.         -1.        ]
 [ 0.          1.41421356]
 [ 0.          0.        ]]


(4)

In [22]:
A = np.array([[4, 8, 1], [0, 2, -2], [3, 6, 7]])

Q, R = QR_classical(A)
print("Classcal method.")
print("Q:\n", Q)
print("R:\n", R, "\n")

Q, R = np.linalg.qr(A, 'complete')
print("Numpy function.")
print("Q:\n", Q)
print("R:\n", R)

Classcal method.
Q:
 [[ 0.8  0.  -0.6]
 [ 0.   1.   0. ]
 [ 0.6  0.   0.8]]
R:
 [[ 5. 10.  5.]
 [ 0.  2. -2.]
 [ 0.  0.  5.]] 

Numpy function.
Q:
 [[-0.8  0.  -0.6]
 [-0.   1.   0. ]
 [-0.6  0.   0.8]]
R:
 [[ -5. -10.  -5.]
 [  0.   2.  -2.]
 [  0.   0.   5.]]


In [23]:
# (b)

Modified QR Decomposition<br>(1)

In [24]:
A = np.array([[4, 0], [3, 1]])

Q, R = QR_modified(A)
print("Classcal method.")
print("Q:\n", Q)
print("R:\n", R, "\n")

Q, R = np.linalg.qr(A, 'complete')
print("Numpy function.")
print("Q:\n", Q)
print("R:\n", R)

Classcal method.
Q:
 [[ 0.8 -0.6]
 [ 0.6  0.8]]
R:
 [[5.  0.6]
 [0.  0.8]] 

Numpy function.
Q:
 [[-0.8 -0.6]
 [-0.6  0.8]]
R:
 [[-5.  -0.6]
 [ 0.   0.8]]


(2)

In [25]:
A = np.array([[1, 2], [1, 1]])

Q, R = QR_modified(A)
print("Classcal method.")
print("Q:\n", Q)
print("R:\n", R, "\n")

Q, R = np.linalg.qr(A, 'complete')
print("Numpy function.")
print("Q:\n", Q)
print("R:\n", R)

Classcal method.
Q:
 [[ 0.70710678  0.70710678]
 [ 0.70710678 -0.70710678]]
R:
 [[1.41421356 2.12132034]
 [0.         0.70710678]] 

Numpy function.
Q:
 [[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
R:
 [[-1.41421356 -2.12132034]
 [ 0.         -0.70710678]]


(3)

In [26]:
A = np.array([[2, 1], [1, -1], [2, 1]])

Q, R = QR_modified(A)
print("Classcal method.")
print("Q:\n", Q)
print("R:\n", R, "\n")

Q, R = np.linalg.qr(A, 'complete')
print("Numpy function.")
print("Q:\n", Q)
print("R:\n", R)

Classcal method.
Q:
 [[ 6.66666667e-01  2.35702260e-01 -7.07106781e-01]
 [ 3.33333333e-01 -9.42809042e-01  8.50529726e-17]
 [ 6.66666667e-01  2.35702260e-01  7.07106781e-01]]
R:
 [[3.         1.        ]
 [0.         1.41421356]
 [0.         0.        ]] 

Numpy function.
Q:
 [[-6.66666667e-01  2.35702260e-01 -7.07106781e-01]
 [-3.33333333e-01 -9.42809042e-01 -2.49800181e-16]
 [-6.66666667e-01  2.35702260e-01  7.07106781e-01]]
R:
 [[-3.         -1.        ]
 [ 0.          1.41421356]
 [ 0.          0.        ]]


(4)

In [27]:
A = np.array([[4, 8, 1], [0, 2, -2], [3, 6, 7]])

Q, R = QR_modified(A)
print("Classcal method.")
print("Q:\n", Q)
print("R:\n", R, "\n")

Q, R = np.linalg.qr(A, 'complete')
print("Numpy function.")
print("Q:\n", Q)
print("R:\n", R)

Classcal method.
Q:
 [[ 0.8  0.  -0.6]
 [ 0.   1.   0. ]
 [ 0.6  0.   0.8]]
R:
 [[ 5. 10.  5.]
 [ 0.  2. -2.]
 [ 0.  0.  5.]] 

Numpy function.
Q:
 [[-0.8  0.  -0.6]
 [-0.   1.   0. ]
 [-0.6  0.   0.8]]
R:
 [[ -5. -10.  -5.]
 [  0.   2.  -2.]
 [  0.   0.   5.]]


### Q. 5

In [28]:
# (a)
A = np.array([[1, 1], [2, 1], [1, 2], [0, 3]])
b = np.array([3, 5, 5, 5])
m, n = A.shape

Q, R = np.linalg.qr(A, 'complete')

In [29]:
d = np.dot(Q.T, b)

x = np.linalg.inv(R[:n]).dot(d[:n])
error = np.sqrt(sum(d[n:]**2) / m)

print("x:", x)
print("RMSE: %f" % error)

x: [1.61538462 1.66153846]
RMSE: 0.151911


In [30]:
# (b)
A = np.array([[1, 2, 2], [2, -1, 2], [3, 1, 1], [1, 1, -1]])
b = np.array([10, 5, 10, 3])
m, n = A.shape

Q, R = np.linalg.qr(A, 'complete')

In [31]:
d = np.dot(Q.T, b)

x = np.linalg.inv(R[:n]).dot(d[:n])
error = np.sqrt(sum(d[n:]**2) / m)

print("x:", x)
print("RMSE: %f" % error)

x: [2.05882353 2.37254902 1.57843137]
RMSE: 0.110702


### Q. 6

In [32]:
# (a)
A = np.array([[3, -1, 2], [4, 1, 0], [-3, 2, 1], [1, 1, 5], [-2, 0, 3]])
b = np.array([10, 10, -5, 15, 0])
m, n = A.shape

Q, R = np.linalg.qr(A, 'complete')

In [33]:
d = np.dot(Q.T, b)

x = np.linalg.inv(R[:n]).dot(d[:n])
error = np.sqrt(sum(d[n:]**2) / m)

print("x:", x)
print("RMSE: %f" % error)

x: [2.5246085  0.66163311 2.09340045]
RMSE: 1.079346


In [34]:
# (b)
A = np.array([[4, 2, 3, 0], [-2, 3, -1, 1], [1, 3, -4, 2], [1, 0, 1, -1], [3, 1, 3, -2]])
b = np.array([10, 0, 2, 0, 5])
m, n = A.shape

Q, R = np.linalg.qr(A, 'complete')

In [35]:
d = np.dot(Q.T, b)

x = np.linalg.inv(R[:n]).dot(d[:n])
error = np.sqrt(sum(d[n:]**2) / m)

print("x:", x)
print("RMSE: %f" % error)

x: [1.27389608 0.6885086  1.21244902 1.74968966]
RMSE: 0.369237


### Q. 7

In [36]:
# (a)
n = 6

hilbert = np.ones((10, 10))
for i in range(10):
    for j in range(10):
        hilbert[i, j] /= (1 + i + j)
        
A = hilbert[:, :n]
c = np.ones(n)
b = np.dot(A, c)

In [37]:
Q, R = np.linalg.qr(A, 'complete')
d = np.dot(Q.T, b)

x = np.linalg.inv(R[:n]).dot(d[:n])
error = np.sqrt(sum((x - c)**2) / n)

print("x:", x)
print("Error: %.10f" % error)

x: [1. 1. 1. 1. 1. 1.]
Error: 0.0000000000


In [38]:
# (b)
n = 8

hilbert = np.ones((10, 10))
for i in range(10):
    for j in range(10):
        hilbert[i, j] /= (1 + i + j)
        
A = hilbert[:, :n]
c = np.ones(n)
b = np.dot(A, c)

In [39]:
Q, R = np.linalg.qr(A, 'complete')
d = np.dot(Q.T, b)

x = np.linalg.inv(R[:n]).dot(d[:n])
error = np.sqrt(sum((x - c)**2) / n)

print("x:", x)
print("Error: %.10f" % error)

x: [1.         1.         0.99999999 1.00000005 0.99999988 1.00000016
 0.99999989 1.00000003]
Error: 0.0000000832


### Q . 8

In [40]:
# (a)
d = 5

x_i = np.linspace(2, 4, 11)
A = np.ones((d+1, 11))
for i in range(1, d+1):
    A[i] = x_i**i
A = A.T
b = np.sum(A, axis=1)

In [41]:
Q, R = np.linalg.qr(A, 'complete')
d_i = np.dot(Q.T, b)

x = np.linalg.inv(R[:d+1]).dot(d_i[:d+1])
error = np.sqrt(sum((x - np.ones(d+1))**2) / (d+1))

print("x:", x)
print("Error: %.10f" % error)
print("Problem 4.1.9 Error: %.10f" % 0.0003735141150385977)

x: [1. 1. 1. 1. 1. 1.]
Error: 0.0000000003
Problem 4.1.9 Error: 0.0003735141


In [42]:
# (b)
d = 6

x_i = np.linspace(2, 4, 11)
A = np.ones((d+1, 11))
for i in range(1, d+1):
    A[i] = x_i**i
A = A.T
b = np.sum(A, axis=1)

In [43]:
Q, R = np.linalg.qr(A, 'complete')
d_i = np.dot(Q.T, b)

x = np.linalg.inv(R[:d+1]).dot(d_i[:d+1])
error = np.sqrt(sum((x - np.ones(d+1))**2) / (d+1))

print("x:", x)
print("Error: %.10f" % error)
print("Problem 4.1.9 Error: %.10f" % 0.3977554581037068)

x: [1. 1. 1. 1. 1. 1. 1.]
Error: 0.0000000013
Problem 4.1.9 Error: 0.3977554581


In [44]:
# (c)
d = 8

x_i = np.linspace(2, 4, 11)
A = np.ones((d+1, 11))
for i in range(1, d+1):
    A[i] = x_i**i
A = A.T
b = np.sum(A, axis=1)

In [45]:
Q, R = np.linalg.qr(A, 'complete')
d_i = np.dot(Q.T, b)

x = np.linalg.inv(R[:d+1]).dot(d_i[:d+1])
error = np.sqrt(sum((x - np.ones(d+1))**2) / (d+1))

print("x:", x)
print("Error: %.10f" % error)
print("Problem 4.1.9 Error: %.10f" % 48391.96584125488)

x: [0.9999988  1.00000368 0.99999511 1.00000367 0.9999983  1.0000005
 0.99999991 1.00000001 1.        ]
Error: 0.0000024831
Problem 4.1.9 Error: 48391.9658412549
